#!/bin/sh

# Script name
THIS="initU-debian"

# Default IP address
IP="10.1.0.100"

# Default netmask
NETMASK="255.255.0.0"

# Default gateway
GATEWAY="10.0.0.1"

# Default nameserver
NAMESERVER="10.0.0.1"

############################################################
## No configurable variables past this point              ##
############################################################

if [ ! -e /sbin/$THIS ] ; then
  echo "This doesn't look like a guest filesystem!"
  exit 1
fi

VERBOSE=""
DRYRUN=""

version () {
  echo >&2 "$THIS version "1
  exit 1
}

usage () {
  echo >&2 "$THIS, initialize a guest filesystem"
  echo >&2
  echo >&2 "Usage: $THIS [options] hostname"
  echo >&2
  echo >&2 "General options"
  echo >&2 "  -n, --dry-run               Don't actually run any commands; just print them."
  echo >&2
  echo >&2 "Networking options"
  echo >&2 "  -I, --ip address            Set the IP address"
  echo >&2 "  -N, --netmask address       Set the netmask"
  echo >&2 "  -G, --gateway address       Set the gateway"
  echo >&2 "  -D, --nameserver address    Set the DNS nameserver address"
  echo >&2
  echo >&2 "Miscellaneous options"
  echo >&2 "  -h, --help                  Display this help and exit"
  echo >&2 "  -v, --verbose               Print informative messages"
  echo >&2 "  --version                   Output version information and exit"
  echo >&2
  exit 1
}

############################################################
## General functions
############################################################

verbose_echo () {
  if test "x$VERBOSE" != "x"; then
    echo $*
  fi
}

#
# try_run desc cmd
#
try_run () {
  desc=$1
  shift
   verbose_echo ==========================================================================
  verbose_echo $desc ...

  if test "x$DRYRUN" != "x" || test "x$VERBOSE" != "x"; then
    echo $*
  fi
  if test "x$DRYRUN" = "x" ; then
    eval $*
    if test "$?" != "0"; then
      echo "$THIS: Failed command:"
      echo $*
      exit 1
    fi
  fi
}

############################################################
## BEGIN: Parse options
############################################################

GETOPTEST=`getopt --version`
SHORTOPTS="nhv"

case $GETOPTEST in
getopt*) # GNU getopt
  TEMP=`getopt -l dry-run -l verbose -l version -l help -- +$SHORTOPTS $@`
  ;;
*) # POSIX getopt ?
  TEMP=`getopt $SHORTOPTS $@`
  ;;
esac

if test "$?" != "0"; then
  usage
fi

eval set -- "$TEMP"

while test "X$1" != "X--"; do
  case "$1" in
    -n|--dry-run)
      DRYRUN="y"
      ;;
    -v|verbose)
      VERBOSE="y"
      ;;
    --version)
      version
      ;;
    -h|--help)
      usage
      ;;
  esac
  shift
done

# Check that all options parsed ok
if test "x$1" != "x--"; then
  usage
fi
shift #get rid of the '--'

if test "x$1" = "x"; then
  usage
fi

############################################################
## Setup
############################################################

GUEST_NAME=$1

echo $GUEST_NAME > /etc/hostname

cat > /etc/hosts << EOF
127.0.0.1       localhost.localdomain   localhost
$IP      $GUEST_NAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

cat > /etc/fstab << EOF
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc		/proc	proc	defaults		0	0
/dev/hda1	/	ext3	errors=remount-ro	0	1
EOF

cd /dev
./MAKEDEV tty1 tty2 tty3 tty4 tty5 tty6

cat > /etc/network/interfaces << EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).
 
# The loopback network interface
auto lo
iface lo inet loopback
 
# The primary network interface
auto eth0
iface eth0 inet dhcp
EOF

apt-get update
apt-get -y dist-upgrade

# Prepare grub and /etc/kernel-img.conf
apt-get -y install grub

cat > /etc/kernel-img.conf << EOF
# Kernel image management overrides
# See kernel-img.conf(5) for details
do_symlinks = yes
relative_links = yes
do_bootloader = no
do_bootfloppy = no
do_initrd = yes
link_in_boot = no
postinst_hook = update-grub
postrm_hook   = update-grub
EOF
