#!/bin/sh

# Script name
THIS="initU-ubuntu"

## A local Ubuntu mirror
##UBUNTU_MIRROR="http://jp.archive.ubuntu.com/ubuntu"
#
## Ubuntu release name
##DEFAULT_RELEASE="hardy"

## Kernel package
#KERNEL_VERSION="2.6.24-16-generic"
#KERNEL="linux-image-$KERNEL_VERSION"

# Default IP address
IP="10.1.0.100"

# Default netmask
NETMASK="255.255.0.0"

# Default gateway
GATEWAY="10.0.0.1"

# Default nameserver
NAMESERVER="10.0.0.1"

############################################################
## No configurable variables past this point              ##
############################################################

if [ ! -e /sbin/$THIS ] ; then
  echo "This doesn't look like a guest filesystem!"
  exit 1
fi

VERBOSE=""
DRYRUN=""

version () {
  echo >&2 "$THIS version "1
  exit 1
}

usage () {
  echo >&2 "$THIS, initialize an Ubuntu guest filesystem"
  echo >&2
  echo >&2 "Usage: $THIS [options] hostname"
  echo >&2
  echo >&2 "General options"
  echo >&2 "  -n, --dry-run               Don't actually run any commands; just print them."
  echo >&2
  echo >&2 "Networking options"
  echo >&2 "  -I, --ip address            Set the IP address"
  echo >&2 "  -N, --netmask address       Set the netmask"
  echo >&2 "  -G, --gateway address       Set the gateway"
  echo >&2 "  -D, --nameserver address    Set the DNS nameserver address"
  echo >&2
  echo >&2 "Miscellaneous options"
  echo >&2 "  -h, --help                  Display this help and exit"
  echo >&2 "  -v, --verbose               Print informative messages"
  echo >&2 "  --version                   Output version information and exit"
  echo >&2
  exit 1
}

############################################################
## General functions
############################################################

verbose_echo () {
  if test "x$VERBOSE" != "x"; then
    echo $*
  fi
}

#
# try_run desc cmd
#
try_run () {
  desc=$1
  shift
   verbose_echo ==========================================================================
  verbose_echo $desc ...

  if test "x$DRYRUN" != "x" || test "x$VERBOSE" != "x"; then
    echo $*
  fi
  if test "x$DRYRUN" = "x" ; then
    eval $*
    if test "$?" != "0"; then
      echo "$THIS: Failed command:"
      echo $*
      exit 1
    fi
  fi
}

############################################################
## BEGIN: Parse options
############################################################

GETOPTEST=`getopt --version`
SHORTOPTS="nhvI:N:G:D:"

case $GETOPTEST in
getopt*) # GNU getopt
  TEMP=`getopt -l dry-run -l verbose -l version -l help -l ip:: -l netmask:: -l gateway:: -l nameserver:: -- +$SHORTOPTS $@`
  ;;
*) # POSIX getopt ?
  TEMP=`getopt $SHORTOPTS $@`
  ;;
esac

if test "$?" != "0"; then
  usage
fi

eval set -- "$TEMP"

while test "X$1" != "X--"; do
  case "$1" in
    -n|--dry-run)
      DRYRUN="y"
      ;;
    -v|verbose)
      VERBOSE="y"
      ;;
    --version)
      version
      ;;
    -h|--help)
      usage
      ;;

    -I|--ip)
      shift
      IP=$1
      ;;
    -N|--netmask)
      shift
      NETMASK=$1
      ;;
    -G|--gateway)
      shift
      GATEWAY=$1
      ;;
    -D|--nameserver)
      shift
      NAMESERVER=$1
      ;;
  esac
  shift
done

# Check that all options parsed ok
if test "x$1" != "x--"; then
  usage
fi
shift #get rid of the '--'

if test "x$1" = "x"; then
  usage
fi

############################################################
### Setup
#############################################################
#
#cat > /etc/apt/sources.list << EOF
#deb $UBUNTU_MIRROR $UBUNTU_RELEASE main
#deb-src $UBUNTU_MIRROR $UBUNTU_RELEASE main
#deb http://security.ubuntu.com/ubuntu $UBUNTU_RELEASE-security main
#EOF
